### ISSUE TITLE
Aineiston järjestäminen

### ISSUE THREAD

**Issue by jukop** [jukop/r_intro#2]
Aineiston järjestäminen sort-funktiolla ja dat[order(dat$x,decreasing=TRUE),] puuttuu materiaalista. Voisi myös mainita, että järjestäminen ei tyypillisesti vaikuta analyysien tuloksiin, koska havaintoriveillä ei tavallisesti ole luontaista järjestystä (poikkeama tähän on toki aikasarja-aineisto).

**Comment by jukop** [comment]
Funktiot sort ja order olisi syytä käydä läpi.

Osiossa 7 tarvitaan myös funktioita names (tai colnames).

**Comment by santikka** [comment]
Lisäsin Data Wrangling lukuun osion Datakehikon ja vektorin järjestäminen.
